trigger: none

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted Ubuntu agent

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:

    - task: AzureCLI@2
      displayName: 'Terraform Init & Plan'
      inputs:
        azureSubscription: 'WifSC'  # Your WIF-enabled service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 

          echo "🔵 Terraform Init"
          terraform init -reconfigure

          echo "🔵 Terraform Plan"
          terraform plan
 