trigger: none

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted Ubuntu agent

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:

  #  - task: TerraformInstaller@1
   #   displayName: 'Install Terraform'
    #  inputs:
     #   terraformVersion: 'latest'  # You can also specify a version like '1.6.6'

    - task: AzureCLI@2
      displayName: 'Terraform Init & Plan'
      inputs:
        azureSubscription: 'WifSC'  # Your WIF-enabled service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 

          echo "🔵 Terraform Init"
          terraform init -reconfigure

          echo "🔵 Terraform Plan"
          terraform plan
 