trigger: none

pool:
  vmImage: 'windows-latest'  # Microsoft-hosted agent

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:

    - task: AzureCLI@2
      displayName: 'Install Terraform'
      inputs:
        azureSubscription: 'WifSC'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/ -UseBasicParsing | Out-String | ForEach-Object {
            if ($_ -match 'terraform/(\d+\.\d+\.\d+)/') {
              $version = $matches[1]
              break
            }
          }
          Write-Output "Installing Terraform version $version"
          $tfUrl = "https://releases.hashicorp.com/terraform/$version/terraform_${version}_windows_amd64.zip"
          Invoke-WebRequest -Uri $tfUrl -OutFile terraform.zip
          Expand-Archive terraform.zip -DestinationPath "$env:USERPROFILE\terraform" -Force
          $env:PATH += ";$env:USERPROFILE\terraform"
          terraform -version

    - task: AzureCLI@2
      displayName: 'Terraform Init & Plan'
      inputs:
        azureSubscription: 'WifSC'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $ErrorActionPreference = "Stop"

          Write-Output "🔵 Setting environment variables for Terraform"
          $env:ARM_SUBSCRIPTION_ID = (az account show --query id -o tsv)
          $env:ARM_TENANT_ID = (az account show --query tenantId -o tsv)
          $env:ARM_CLIENT_ID = $env:servicePrincipalId
          $env:ARM_CLIENT_SECRET = $env:servicePrincipalKey

          Write-Output "🔵 Terraform Init"
          terraform init -reconfigure

          Write-Output "🔵 Terraform Plan"
          terraform plan

